---
name: HTML-FormHandler-Render-Hash
version: 0.01
author:
  - 'Michael Nachbaur <mike@nachbaur.com>'
abstract: render a form to a raw hash
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTML::FormHandler: 0
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  HTML::FormHandler::Render::Hash:
    file: lib/HTML/FormHandler/Render/Hash.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
